version: '2'
services:
    prototype-app:
        image: prototype
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prototype-mysql:3306/prototype?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    prototype-mysql:
        extends:
            file: mysql.yml
            service: prototype-mysql
